# ==========================================
# RetroDisc Configuration
# ==========================================


#===========================================
# Game Setup
#===========================================

### Game Title
GAME=""

### Executable relative to this Launcher
GAME_EXE=".exe"

### Additional launch arguments
GAME_ARGS=(
    # "-console"
    # "-window"
)

### Folder name inside RetroDisc
DATA_NAME="" 

# Use the game name followed by "Data".
# Do not use spaces.
# Example: ResidentEvilData

### Start game using Proton (1) or Wine (0)
USE_PROTON=1

LOCALE="en_US.UTF-8"

### Launch the game through Gamescope.
USE_GAMESCOPE=0

### Additional Gamescope arguments
### Quotes are optional unless an argument contains spaces.
GAMESCOPE_ARGS=(
    -f      # Fullscreen
    -r 60   # Refreshrate
)

# ==========================================
# Optional Settings
# ==========================================


# ==========================================
# Proton Configuration
# ==========================================

### Steam Proton Version
PROTON_NAME="Proton - Experimental"

# Examples:
# "Proton - Experimental"
# "Proton 10.0"
# "Proton 9.0"

# ==========================================
# WINE CONFIGURATION
# ==========================================

### Windows version used by Wine
# Possible:
# win98
# win2000
# winxp
# win7
# win8
# win10
# win11
WINE_WINDOWS_VERSION="win7"


### DLL overrides
# Example:
# ddraw=n,b
WINEDLLOVERRIDES=""

### DirectDraw renderer
## opengl
## gdi
WINE_RENDERER="gl"
WINE_VIDEO_MEMORY="8192"

### Start in fullscreen
# 0 = window
# 1 = fullscreen
WINE_FULLSCREEN=0

### Enable DXVK
# 0 = WineD3D
# 1 = DXVK
USE_DXVK=0

### Enable Sync
USE_ESYNC=1
USE_FSYNC=1

### Allow window manager to decorate windows
WINE_ALLOW_WINDOW_DECORATION=1

### Allow window manager to control windows
WINE_ALLOW_WINDOW_MANAGER=1

### Capture mouse in fullscreen mode
WINE_MOUSE_CAPTURE=1

### Enable Wine virtual desktop
# 0 = disabled
# 1 = enabled
WINE_VIRTUAL_DESKTOP=0

WINE_MOUSE_CAPTURE=1
WINE_STRICT_DRAW_ORDERING=0

### Virtual desktop resolution
# Only used when WINE_VIRTUAL_DESKTOP=1
WINE_DESKTOP_WIDTH=640
WINE_DESKTOP_HEIGHT=480

WINE_DPI=96

# ==========================================
# Environment Variables
# ==========================================

### Additional environment variables
# Format:
# "NAME=VALUE"
#
# Examples:
# "DXVK_HUD=1"
# "MANGOHUD=1"
# "__GL_THREADED_OPTIMIZATIONS=1"
# "MESA_VK_WSI_PRESENT_MODE=mailbox"

### Quotes are optional unless an argument contains spaces.
ENV_VARS=(
)