#include "prefix_internal.hpp"

#include <filesystem>
#include <iostream>
#include <system_error>


namespace prefix_internal
{


/*
    ================================================================
    ENSURE WINE USER SYMLINK
    ================================================================

    Wine always uses RetroDisc as the canonical Windows user.

    The Unix username is linked to that directory so that paths
    generated by Wine using the Unix account name resolve to the
    same persistent Windows profile.

        drive_c/users/
        ├── RetroDisc/
        └── <unix-user> -> RetroDisc

    This is part of the persistent UPPER. It is therefore a
    game-specific delta and is never written to the global LOWER.
*/


bool ensureWineUserSymlink(
    const std::filesystem::path& persistentPrefix
)
{
    const auto unixUsername =
        getUnixUsername();

    if(unixUsername.empty())
    {
        std::cerr
            << "Could not determine Unix username."
            << std::endl;

        return false;
    }


    const auto usersDirectory =
        persistentPrefix /
        "drive_c" /
        "users";


    const auto canonicalUserDirectory =
        usersDirectory /
        "RetroDisc";


    const auto unixUserPath =
        usersDirectory /
        unixUsername;


    std::error_code ec;


    std::filesystem::create_directories(
        canonicalUserDirectory,
        ec
    );

    if(ec)
    {
        std::cerr
            << "Could not create RetroDisc Windows user directory:"
            << std::endl
            << "    "
            << canonicalUserDirectory
            << std::endl
            << "    "
            << ec.message()
            << std::endl;

        return false;
    }


    const auto status =
        std::filesystem::symlink_status(
            unixUserPath,
            ec
        );


    if(!ec)
    {
        if(std::filesystem::is_symlink(status))
        {
            const auto existingTarget =
                std::filesystem::read_symlink(
                    unixUserPath,
                    ec
                );

            if(
                !ec &&
                existingTarget == std::filesystem::path(
                    "RetroDisc"
                )
            )
            {
                return true;
            }


            if(ec)
            {
                std::cerr
                    << "Could not inspect existing Wine user symlink:"
                    << std::endl
                    << "    "
                    << unixUserPath
                    << std::endl
                    << "    "
                    << ec.message()
                    << std::endl;

                return false;
            }


            std::filesystem::remove(
                unixUserPath,
                ec
            );

            if(ec)
            {
                std::cerr
                    << "Could not replace existing Wine user symlink:"
                    << std::endl
                    << "    "
                    << unixUserPath
                    << std::endl
                    << "    "
                    << ec.message()
                    << std::endl;

                return false;
            }
        }
        else
        {
            /*
                Never delete a real user directory/file just to
                create our compatibility symlink.
            */

            std::cerr
                << "Wine Unix-user path already exists and is not"
                << " a symlink:"
                << std::endl
                << "    "
                << unixUserPath
                << std::endl;

            return false;
        }
    }
    else if(
        ec != std::errc::no_such_file_or_directory
    )
    {
        std::cerr
            << "Could not inspect Wine Unix-user path:"
            << std::endl
            << "    "
            << unixUserPath
            << std::endl
            << "    "
            << ec.message()
            << std::endl;

        return false;
    }


    ec.clear();


    std::filesystem::create_symlink(
        "RetroDisc",
        unixUserPath,
        ec
    );


    if(ec)
    {
        std::cerr
            << "Could not create Wine Unix-user compatibility symlink:"
            << std::endl
            << "    "
            << unixUserPath
            << " -> RetroDisc"
            << std::endl
            << "    "
            << ec.message()
            << std::endl;

        return false;
    }


    std::cout
        << "Wine user compatibility symlink:"
        << std::endl
        << "    "
        << unixUserPath
        << " -> RetroDisc"
        << std::endl;


    return true;
}


} // namespace prefix_internal
